config/routes.rb
Rails.application.routes.draw do
  root "tops#home"
  get "features", to: "tops#about"
  get "help",     to: "tops#help"
  get "contact",  to: "tops#contact"
  get "/signup",  to: "users#new"

  resources :users, except: [:new]
  resources :orders
  resources :medicines, only: [:show, :index]
  resources :messages
  resources :message_contents

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


def hello

 end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController

    def index
    end

    def show
    end
end

app/controllers/message_contents_controller.rb
class MessageContentsController < ApplicationController

       def new
      end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    def new
    end

    def index
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    #各ページにタイトルを渡す
    def full_title(page_title ="")
        base_title = "Medical App"
        if page_title.empty?
            base_title
        else
            page_title + "|" + base_title
        end
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/message_contents_helper.rb
module MessageContentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Features",   features_path%></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Medical app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Features",   features_path %></li>
            <li><%= link_to "Search",   medicines_path %></li>
            <li><%= link_to "Help",   help_path %></li>
                                 <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
           </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%=render 'layouts/head'%>
<body>
  <%=render 'layouts/header'%>
    <div class="container">
    <%= yield %>
    <%=render 'layouts/footer'%>
    </div>
</body>
</html>

app/views/medicines/index.html.erb
<h1>医薬品 検索</h1>

   <p>症状からお選びください</p>

    <li><%= link_to "医薬品詳細", "#"%>

app/views/medicines/show.html.erb
<h1>医薬品一覧</h1>

<p>症状からお選びください</p>

<li><%= link_to "医薬品詳細",　medicines _path %></li>

app/views/message_contents/index.html.erb
<h1>ユーザー相談内容　履歴/h1>

app/views/message_contents/new.html.erb
<h1>相談入力画面</h1>

<%= form_with model: @user do |f|  %>
  <%= f.text_field :content %>
  <%= f.submit '送信'%>
<% end %>

app/views/message_contents/show.html.erb
<h1>ユーザーと管理者との相談画面</h1>

app/views/orders/index.html.erb
<h1>注文履歴</h1>

app/views/orders/new.html.erb
<h1>注文入力フォーム</h1>

app/views/shared/_test_login.html.erb
<%= form_with url:"#" do |f| %>
      <div class="test-user">
        <i class="fas fa-user"></i>
        <%= f.hidden_field :email, value: "test@example.com" %>
        <%= f.hidden_field :password, value: "123456" %>
        <%= f.submit 'テストログイン', class: "btn btn-lg btn-primary" %>
      </div>
<% end %>

app/views/tops/about.html.erb
<%provide(:title, 'Features')%>
<h1>Features</h1>
<p>
  どういった薬を飲めばいいのか。薬の飲み合わせ等、そういった心配や健康に関する相談にお応えするサービスです。
  お客様一人ひとりの持薬・持病をご登録頂くことで健康管理にもつながります。
  また、季節ごとに沿った健康に関する情報を随時お届けします。
  <a href="#">健康情報</a>.
</p>

app/views/tops/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/tops/help.html.erb
<%provide(:title, 'help')%>

<h1>どのようなことでお困りですか？</h1>

<p>検索フォーム</p>

app/views/tops/home.html.erb
<div class="center jumbotron">
  <h1>Medical App</h1>

  <p>
    医療をより身近に感じられるような医療フォームを整えることで遠くからでも医療にコンタクトできる時代へ
  </p>

  <%=render 'shared/test_login' %>

  <%=link_to "新規登録", signup_path, class: "btn btn-lg btn-primary"%>
  </div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>
<p>こちらから新規ユーザーの登録を行うことができます</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for("") do |f| %>
      <%= f.label :name, "ユーザー名"%>  
      <%= f.text_field :name %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email%>

      <%= f.label :password, "パスワード"%>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "パスワード再確認" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
  </div>
  <%=render 'shared/test_login'%>
</div>